openapi: 3.0.0
info:
  title: Vehicle API
  description: API for managing vehicles
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /vehicles:
    get:
      summary: Get all vehicles
      responses:
        '200':
          description: List of vehicles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
    post:
      summary: Create a new vehicle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
      responses:
        '201':
          description: Vehicle created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
  /vehicles/{id}:
    get:
      summary: Get a vehicle by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Vehicle details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '404':
          description: Vehicle not found
    put:
      summary: Update a vehicle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
      responses:
        '200':
          description: Vehicle updated
        '404':
          description: Vehicle not found
    delete:
      summary: Delete a vehicle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Vehicle deleted
        '404':
          description: Vehicle not found
components:
  schemas:
    Vehicle:
      type: object
      properties:
        id:
          type: integer
        placa:
          type: string
        chassi:
          type: string
        renavam:
          type: string
        modelo:
          type: string
        marca:
          type: string
        ano:
          type: integer
      required:
        - placa
        - chassi
        - renavam
        - modelo
        - marca
        - ano
